import { NextResponse } from 'next/server';
import { getConnection } from '@/lib/db';
import sql from 'mssql';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const csdStartDateStr = searchParams.get('csdStartDate'); 
  const csdEndDateStr = searchParams.get('csdEndDate'); 
  const offerStartDateStr = searchParams.get('offerStartDate'); 
  const offerEndDateStr = searchParams.get('offerEndDate'); 
  const sirkodStr = searchParams.get('sirkod') || '1';

  if (!csdStartDateStr || !csdEndDateStr || !offerStartDateStr || !offerEndDateStr) {
    return NextResponse.json({ error: 'All date parameters (CSD and Offer) are required' }, { status: 400 });
  }

  try {
    const pool = await getConnection();
    
    // Using the exact structure from merged_report_query.sql matched to user's requirements
    const query = `
      SELECT 
          t.SASINO AS VIN,
          a.MARKA,
          t.TEKLIFTAR,
          t.GECERTAR,
          t.CSDDATE,
          t.TAVMAKTAR,
          a.USTMODEL AS [Product Line],
          m.ACIKLAMA AS MODEL_ACIKLAMA,
          k.ADISOY AS SATIS_DANISMANI,
          f.UNVAN AS MUSTERI_UNVAN,

          -- Aggregated amounts from the single pass OUTER APPLY
          ISNULL(inv_agg.SumStandartBRFIYAT, 0) + ISNULL(a.DISTPROMTUT, 0) AS [Vehicle Nett Amount],
          ISNULL(inv_agg.SumDonanimBRFIYAT, 0) AS [Options Nett Amount],
          ISNULL(inv_agg.SumISKONTO, 0) AS [Cash Payment Discount],
          ISNULL(a.DISTPROMTUT, 0) AS [Promotion Amount],
          
          -- Excel'deki ek alanlar
          CASE WHEN m.ARACTIPI = 'TV' THEN 'LCV' ELSE 'PC' END AS [Class],
          m.ACIKLAMA AS [Commercial Denomination Name],
          a.SASINO AS VIN_2,
          a.MODELYILI AS [Model Year],
          a.SATICI AS [Dealer Id],
          'ALPATA' AS [Dealer Name], 
          CONVERT(VARCHAR(10), fm.FATTAR, 104) AS [Invoice Date],
          fm.FATNO AS [Invoice No],
          fm.EFATNO AS [Preprinted Invoice Number],
          CONVERT(VARCHAR(10), fm.VADETAR, 104) AS [Payment Term Date],
          DATEDIFF(day, fm.FATTAR, fm.VADETAR) AS [Free Interest Days],
          
          ISNULL(inv_agg.SumBRFIYAT, 0) + ISNULL(a.DISTPROMTUT, 0) AS [HT Price],
          ISNULL(inv_agg.SumBRFIYAT, 0) + ISNULL(a.DISTPROMTUT, 0) AS [Total Nett Amount]
          
      FROM [37.131.251.91, 10168].[peugeotdms].[dbo].[ATEKLIF0] AS t

      JOIN [37.131.251.91, 10168].[peugeotdms].[dbo].[GNLKULL0] AS k
          ON k.SICILNO = t.SATICISICIL
         AND k.SIRKOD  = t.SIRKOD

      JOIN [37.131.251.91, 10168].[peugeotdms].[dbo].[AARAC0] AS a
          ON a.SASINO = t.SASINO
         AND a.SIRKOD = t.SIRKOD

      LEFT JOIN [37.131.251.91, 10168].[peugeotdms].[dbo].[AMODEL0] AS m
          ON m.SIRKOD = a.SIRKOD
         AND m.MODEL  = a.MODEL

      LEFT JOIN [37.131.251.91, 10168].[peugeotdms].[dbo].[GNLFIRMA0] AS f
          ON f.SIRKOD  = t.SIRKOD
         AND f.VERGINO = t.FIRMA

      -- 1) Satınalma (Gelen) Faturaları (En güncel fatura)
      OUTER APPLY (
          SELECT TOP 1 
              fm_sub.FATNO, fm_sub.FATTAR, fm_sub.VADETAR, fm_sub.EFATNO
          FROM [37.131.251.91, 10168].[peugeotdms].[dbo].[UFATMAS0] fm_sub
          JOIN [37.131.251.91, 10168].[peugeotdms].[dbo].[UFATDET0] fd_sub ON fm_sub.FATNO = fd_sub.FATNO
          WHERE fm_sub.EFATNO LIKE 'PE%' AND fd_sub.SASINO = a.SASINO
          ORDER BY fm_sub.FATTAR DESC, fm_sub.FATNO DESC
      ) fm

      -- 2) Network gecikmesini (N+1) onlemek icin Subquery'leri tek grupta toplama
      OUTER APPLY (
          SELECT 
              SUM(CASE WHEN fd_agg.DMBGRUP = 'STANDART' THEN fd_agg.BRFIYAT ELSE 0 END) AS SumStandartBRFIYAT,
              SUM(CASE WHEN fd_agg.DMBGRUP = 'DONANIM' THEN fd_agg.BRFIYAT ELSE 0 END) AS SumDonanimBRFIYAT,
              SUM(fd_agg.BRFIYAT) AS SumBRFIYAT,
              SUM(fd_agg.ISKONTO) AS SumISKONTO
          FROM [37.131.251.91, 10168].[peugeotdms].[dbo].[UFATDET0] fd_agg
          WHERE fd_agg.FATNO = fm.FATNO AND fd_agg.SASINO = a.SASINO
      ) inv_agg

      WHERE
           t.CSDDATE >= '${csdStartDateStr} 00:00:00.000'
          AND t.CSDDATE < '${csdEndDateStr} 00:00:00.000'
          AND t.GECERTAR >= '${offerStartDateStr} 00:00:00.000'
          AND t.GECERTAR < '${offerEndDateStr} 00:00:00.000'
          AND a.SIRKOD = ${Number(sirkodStr)}
      ORDER BY t.SASINO, t.SIRKOD;
    `;

    const request = pool.request();
    
    // Using string interpolation directly since dates are strictly generated by the server, 
    // to bypass mssql type scanning which causes full table scans on this database.
    const result = await request.query(query);
    
    return NextResponse.json({ data: result.recordset, sqlQuery: query });
  } catch (error: any) {
    console.error('API Error:', error);
    return NextResponse.json({ error: 'Database error', details: error.message }, { status: 500 });
  }
}
